require('sinatra')
require('sinatra/reloader')
also_reload('lib/**/*.rb')
require('./lib/word')
require('./lib/definition')
require('pry')
require('launchy')
require('pg')

DB = PG.connect({:dbname => "doctors_office_test"})
